name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          
      - run: flutter channel stable
      - run: flutter upgrade
      
      - run: flutter config --enable-web
      
      - run: flutter clean 
      
      - run: flutter pub get
      
      - run: flutter pub cache repair
      
      
      - run: flutter build web --base-href "/${{ github.event.repository.name }}/" --release
      - run: pwd
      - run: cd ./build/web
      - run: echo "mindong.uk" > ./build/web/CNAME
      - run: git init
          
      - run: git config --global user.email mindw96@naver.com
      - run: git config --global user.name mindw96
      - run: git status
      
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic update"
      - run: git push origin HEAD:gh-pages --force
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
      
