name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - run: pwd
      - run: cd ./build/web
      - run: git init
          
      - run: git config --global user.email mindw96@naver.com
      - run: git config --global user.name mindw96
      - run: git status
      
      - run: git remote remove origin
      - run: git remote add origin https://github.com/mindw96/web_page.git 
      - run: git checkout -b update-pages
      - run: git add --all
      - run: git commit -m "update"
      - run: git push origin update-pages -f
