name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      apiKey: '${{secrets.OPENAI_KEY}}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          
      # - run: mkdir assets
      # - run: echo "OPENAI_API='${{secrets.OPENAI_KEY}}'" > ./assets/.env
      # - run: cat ./assets/.env

      - run: flutter config --enable-web
      
      - run: flutter pub get
      
      - run: flutter build web --base-href "/" --release
      - run: pwd
      - run: cd ./build/web
      - run: echo "mindong.uk" > ./build/web/CNAME
      # - run: echo "OPENAI_API='${{secrets.OPENAI_KEY}}'" > ./assets/.env
      # - run: cat ./assets/.env
      - run: git init
          
      - run: git config --global user.email mindw96@naver.com
      - run: git config --global user.name mindw96
      - run: git status
      
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic update"
      - run: git push origin HEAD:gh-pages --force
      #
